from param_set import ParamSet

def default_param_set():
  return ParamSet(
    alpha=255,
    num_root_segments=12,
    root_segment_pos_const_x=55,
    root_segment_pos_const_y=300,
    root_segment_pos_linear_x=5,
    root_segment_pos_linear_y=10,
    root_segment_pos_quadratic_x=0,
    root_segment_pos_quadratic_y=0,
    root_segment_len=50,
    root_segment_len_factor=0.9,
    root_segment_dir_const_x=1.0,
    root_segment_dir_const_y=1.0,
    root_segment_dir_linear_x=0,
    root_segment_dir_linear_y=0,
    root_segment_dir_quadratic_x=0,
    root_segment_dir_quadratic_y=0,
    segment_dir_linear_x=0,
    segment_dir_linear_y=0,
    segment_dir_quadratic_x=0,
    segment_dir_quadratic_y=0,
    segment_dir_a_x=0,
    segment_dir_a_y=0,
    segment_dir_b_x=0,
    segment_dir_b_y=0,
    segment_dir_c_x=0,
    segment_dir_c_y=0,
    segment_dir_d_x=0,
    segment_dir_d_y=0,
    segment_len_factor=0.95,
    max_generations_const=12,
    max_generations_linear=0.0,
    max_generations_quadratic=0.0,
    cross_vein_density=0.000845
  )