from typing import TypedDict

class ParamSet(TypedDict):
  alpha: int
  num_root_segments: int
  root_segment_pos_const_x: float
  root_segment_pos_const_y: float
  root_segment_pos_linear_x: float
  root_segment_pos_linear_y: float
  root_segment_pos_quadratic_x: float
  root_segment_pos_quadratic_y: float
  root_segment_len: float
  root_segment_len_factor: float
  root_segment_dir_const_x: float
  root_segment_dir_const_y: float
  root_segment_dir_linear_x: float
  root_segment_dir_linear_y: float
  root_segment_dir_quadratic_x: float
  root_segment_dir_quadratic_y: float
  segment_dir_linear_x: float
  segment_dir_linear_y: float
  segment_dir_quadratic_x: float
  segment_dir_quadratic_y: float
  segment_dir_a_x: float
  segment_dir_a_y: float
  segment_dir_b_x: float
  segment_dir_b_y: float
  segment_dir_c_x: float
  segment_dir_c_y: float
  segment_dir_d_x: float
  segment_dir_d_y: float
  segment_len_factor: float
  max_generations_const: int
  max_generations_linear: float
  max_generations_quadratic: float
  cross_vein_density: float